export const USER_TOKENS = {
  IRegister: 'IRegister',
  IVerifyEmail: 'IVerifyEmail',
  ILogin: 'ILogin',
  IForgotPassword: 'IForgotPassword',
  IResetPassword: 'IResetPassword',
  IRefreshToken: 'IRefreshToken',
  ISendOtp: 'ISendOtp',
  ILogout: 'ILogout',
  IVerifyOtp: 'IVerifyOtp',
  IGoogleAuth: 'IGoogleAuth',
  IOnboardingSource: 'IOnboardingSource',
  ISetProfile: 'ISetProfile',
  ISetTravelStyle: 'ISetTravelStyle',
  IUpdateLocation: 'IUpdateLocation',
  IGetLocation: 'IGetLocation',
  IGetUsersForCard: 'IGetUsersForCard',
  IGetNearbyUsers: 'IGetNearbyUsers',
  IReverseGeoCode: 'IReverseGeoCode',
  IGetUserProfile: 'IGetUserProfile',
} as const;
