export const TRIP_TOKENS = {
  ITripRepository: 'ITripRepository',
  ICreateTrip: 'ICreateTrip',
  ICalculateMatch: 'ICalculateMatch',
  IGetTripMatches: 'IGetTripMatches',
  IGetActiveTrip: 'IGetActiveTrip',
  IGetUserUpcomingTrips: 'IGetUserUpcomingTrips',
  IGetMatchProfile: 'IGetMatchProfile',
  IGetPastTrips: 'IGetPastTrips',
  IEditTrip: 'IEditTrip',
  IDeleteTrip: 'IDeleteTrip',
  ICreateGroup: 'ICreateGroup',
  IGetActiveGroups: 'IGetActiveGroups',
  IAddMembers: 'IAddMembers',
  IGetMembers: 'IGetMembers',
  IGetGroup: 'IGetGroup',
  IGetInviteCode: 'IGetInviteCode',
  ISendInvite: 'ISendInvite',
  IJoinWithLink: 'IJoinWithLink',
  IGetInvites: 'IGetInvites',
  IRemoveMember: 'IRemoveMember',
  IChangeRole: 'IChangeRole',
  IGetWeather: 'IGetWeather',
  IGetAllTripGroups: 'IGetAllTripGroups',
  IGetUserGroups: 'IGetUserGroups',
};
